[workspace]
authors = ["Jakub Marsik <jmarsik@fullvent.cz>"]
channels = ["conda-forge"]
name = "Lekis-ProxmoxTemplates"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[dependencies]
python = "3.13.*"
nodejs = "20.18.*"
packer = ">=1.11"
jq = "*"
bash = "*"

[tasks]
init = "packer init ."
fmt = "packer fmt -recursive ."
validate-2025 = "packer validate -var-file=pkrvars/2025-desktop.pkrvars.hcl ."
validate-2022 = "packer validate -var-file=pkrvars/2022-desktop.pkrvars.hcl ."
build-2025 = "./build.sh 2025-desktop"
build-2022 = "./build.sh 2022-desktop"
