[workspace]
authors = ["Jakub Marsik <jmarsik@fullvent.cz>"]
channels = ["conda-forge", "hcc"]
name = "proxmox-templates-windows-server"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.13.*"
nodejs = "20.18.*"
packer = ">=1.11"
jq = "*"

[activation.env]
# contains "xorriso" pixi-exec-based script that runs xorriso tool as if it was installed on the system
# normally we would just add xorriso to the dependencies, but it's kinda old and not compatible with
#  python 3.13 and a lot of other packages
PATH = "$PIXI_PROJECT_ROOT/tools:$PATH"

[tasks]
init = "packer init ."
fmt = "packer fmt -recursive ."
validate-2025 = "packer validate -var-file=pkrvars/2025-desktop.pkrvars.hcl ."
validate-2022 = "packer validate -var-file=pkrvars/2022-desktop.pkrvars.hcl ."
build-2025 = "./build.sh 2025-desktop"
build-2022 = "./build.sh 2022-desktop"

[pypi-dependencies]
proxmoxer = ">=2.3.0, <3"
requests = ">=2.33.1, <3"
